export const kisaDonemNedenleri = {
  1: "Bilimsel araştırma amacıyla gelecekler",
  2: "Türkiye'de taşınmaz malı bulunanlar",
  3: "Ticari bağlantı veya iş kuracaklar",
  6: "Turizm amaçlı kalacaklar",
  15: "Kamu kurumları aracılığıyla eğitim, araştırma, staj ve kurslara katılacaklar",
  5: "Öğrenci değişim programları çerçevesinde eğitim görecekler",
  17: "Staj amaçlı değişim programları çerçevesinde eğitim görecekler",
  12: "Yükseköğrenimini tamamlayıp 6 ay içinde müracaat edenler",
  4: "Hizmet içi eğitim programlarına katılacaklar",
  9: "İdari makamların kararı",
  8: "İdari makamların talebi",
  18: "6458 sayılı kanunun 31. Maddesinin j bendi kapsamında",
  19: "KKTC Vatandaşı",
  16: "Aile ikamet izninden kısa dönem ikamet iznine geçenler",
  13: "Anlaşmalar çerçevesinde eğitim",
  7: "Tedavi görecekler",
  14: "Türkçe öğrenme kurslarına katılacaklar",
} as const

export const uzunDonemTurkSoylu = {
  1: "KKTC VATANDAŞLARI",
  2: "AHISKA TÜRKÜ",
  3: "ÇEÇEN ASILLI YABANCI",
  4: "KARADENİZ",
  5: "UYGUR TÜRKÜ",
  6: "BULGARİSTAN TÜRKÜ",
  7: "BATI TRAKYA TÜRKÜ",
  8: "IRAK TÜRKMENİ",
  9: "AFGANİSTAN TÜRKÜ",
  10: "KIRIM TATARI",
  11: "ESKİ YUGOSLAVYA UYRUKLU",
  12: "YUNANİSTAN ISKATI",
} as const

export const insaniIkametNedenleri = {
  5: "53. maddeye göre sınır dışı etme kararına karşı yargı yoluna başvurulduğunda",
  4: "55. madde uyarınca yabancı hakkında sınır dışı etme kararı alınmadığında",
  6: "72. maddeye göre kabul edilemez başvuru kararına karşı yargı yoluna başvurulduğunda",
  7: "77. maddeye göre başvurunun geri çekilmesi veya geri çekilmiş sayılmasına karşı yargı yoluna başvuru",
  9: "Acil nedenlerden dolayı Türkiye'de kalmasına izin verilmesi gereken",
  20: "Başvuru sahibinin ilk iltica ülkesi veya güvenli üçüncü ülkeye geri gönderilmesi işlemlerinin devamı süresince",
  8: "Başvuru sahibinin geri gönderilmesi işlemlerinin devamı süresince",
  14: "Ciddi sağlık sorunları nedeniyle seyahat etmesi riskli görülenler",
  1: "Çocuğun yüksek yararı",
  16: "Hamilelik durumu nedeniyle seyahat etmesi riskli görülenler",
  17: "Hayati tehlike arz eden hastalıkları için tedavisi devam etmekteyken...",
  10: "Kamu düzeni ve kamu güvenliği açısından Türkiye'de kalmasına izin verilmesi gereken",
  18: "Mağdur destek sürecinden yararlanmakta olan insan ticareti mağdurları",
  11: "Olağanüstü durumlarda",
  13: "Sınır dışı edileceği ülkede ölüm cezası vs. ciddi emare",
  2: "Sınır dışı/giriş yasağı kararına rağmen çıkışları yaptırılamayan",
  12: "Sınır dışı/giriş yasağına rağmen Türkiye'den ayrılmaları makul görülmeyen",
  19: "Tedavileri tamamlanıncaya kadar psikolojik/ fiziksel mağdurlar",
  3: "Türkiye'den ayrılmaları makul görünmeyen",
  21: "Ülke menfaatleri ile ilgili sebepler",
  15: "Yaş durumu nedeniyle seyahat riskli görülenler",
} as const

export const aileDestekleyiciTur = {
  1: "Destekleyicinin Eşi",
  2: "Destekleyicinin Ergin Olmayan Çocuğu",
  3: "Destekleyicinin Bakmakla Yükümlü Olduğu Çocuğu",
  4: "Destekleyicinin Eşinin Ergin Olmayan Çocuğu",
  5: "Destekleyicinin Eşinin Bakmakla Yükümlü Olduğu Çocuğu",
} as const

export const ogrenciKalisNeden = {
  6: "Açıköğretim – Uzaktan Eğitim Programları",
  9: "Askeri Liseler",
  8: "Askeri Okullarda Öğrenim Görenler",
  20: "Diğer Uluslararası Değişim Programları",
  4: "Diş Hekimliğinde Uzmanlık Eğitimi",
  19: "Doktora",
  2: "Erasmus Programı",
  17: "Harp Okulları",
  10: "İlkokul",
  15: "Lisans - Diş Hek./Ecz./Veterinerlik",
  16: "Lisans - Tıp Fakültesi",
  14: "Lisans",
  12: "Lise",
  7: "MEB'e Bağlı Olmayan Okullarda",
  11: "Ortaokul",
  13: "Ön Lisans",
  1: "Temel Eğitim - Orta-Üst Eğitim",
  3: "Tıpta Uzmanlık Eğitimi",
  5: "Üniversite tarafından Türkçe kursuna yönlendirilenler",
  18: "Yüksek Lisans",
} as const
